import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firt_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXt NOT NULL,
    phone TEXT NOT NULL,
    dob DATE,
    gender TEXT CHECK (gender IN ('m', 'f', 'o')),
    role_type TEXT CHECK (role_type IN ('super_admin', 'artist_manager', 'artist')),
    Address TEXT,
    created_at DATE,
    updated_at DATE
    ) `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`DROP TABLE users`);
}
