/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck1@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck2@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck3@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck4@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck5@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck6@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck7@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck8@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck9@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck10@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck11@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "super_admin",
      address: "kathmandu, nepal",
    },
    {
      first_name: "dipak",
      last_name: "kalauni",
      email: "duckduck12@gmail.com",
      password: "$2a$12$U96Ti2XsM4quDgy23wfRU.JCWYLtpxUjtrw9SBu3VjwSVQLdhCZMW",
      phone: "9868810438",
      dob: new Date("2023-09-01"),
      gender: "m",
      role_type: "artist_manager",
      address: "kathmandu, nepal",
    },
  ]);
};
